name: sync

on: push
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: curl
        uses: wei/curl@master
        with:
          args: ${{ secrets.SYNC_CODING }}
